version: 2

sources:
  - name: raw_public
    database: HEVO_DB
    schema: RAW_PUBLIC

    tables:
      - name: customer_secure

models:

  - name: dim_customers
    columns:

      - name: customer_id
        tests:
          - not_null
          - unique

  - name: fact_orders
    columns:

      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null

  - name: dim_customer_secure
    columns:

      - name: customer_id
        tests:
          - unique
          - not_null

      - name: masked_email
        tests:
          - not_null

      - name: is_deleted
        tests:
          - not_null